import { type CriteriaBuilder, criteriaBuilder } from "@hogsend/core";
import type { BucketMeta, ConditionEval } from "@hogsend/core/types";
import type { DefinedJourney } from "../journeys/define-journey.js";
import type { hatchet } from "../lib/hatchet.js";
import { type BucketAccessor, createBucketAccessor } from "./bucket-access.js";
import {
  type BucketOnHandler,
  buildBucketReaction,
  type DwellOptions,
  type EnterOptions,
  type LeaveOptions,
  normalizeOnArgs,
} from "./bucket-reactions.js";

/**
 * `criteria` may be authored two ways:
 *  - declaratively, as a `ConditionEval` data tree, or
 *  - with the fluent builder, as `(b) => b.all(b.prop("plan").eq("trial"), ...)`.
 * The builder form runs ONCE here and returns a `ConditionEval`, so everything
 * downstream (registry indexes, schema validation, reconcile cron, Studio) only
 * ever sees the canonical declarative data.
 */
export type CriteriaInput =
  | ConditionEval
  | ((b: CriteriaBuilder) => ConditionEval);

/** `BucketMeta` as authored — `criteria` accepts the builder function too. */
export type BucketMetaInput<Id extends string = string> = Omit<
  BucketMeta,
  "criteria" | "id"
> & { id: Id; criteria?: CriteriaInput };

export type { DwellOptions };

export interface DefinedBucket<Id extends string = string> {
  meta: BucketMeta;
  /** Literal-typed transition ref: `"bucket:entered:<id>"`. */
  readonly entered: `bucket:entered:${Id}`;
  /** Literal-typed transition ref: `"bucket:left:<id>"`. */
  readonly left: `bucket:left:${Id}`;
  /**
   * The only task a bucket ever holds is the opt-in per-user fast-expiry timer,
   * which is a DURABLE task (it `ctx.sleepFor`s — Section 6.5), so the type MUST
   * be the durableTask return type, mirroring
   * `DefinedJourney.task = ReturnType<typeof hatchet.durableTask>`
   * (define-journey.ts:34) — NOT `hatchet.task`. The common case is
   * declarative-only (no task), like webhookSources; the engine-wide
   * `bucketReconcileTask` handles time-based leaves regardless.
   */
  task?: ReturnType<typeof hatchet.durableTask>;
  /** Reaction journeys generated by `.on()`. Read by the worker + container. */
  reactions: DefinedJourney[];
  count: BucketAccessor["count"];
  has: BucketAccessor["has"];
  members: BucketAccessor["members"];
  membersIterator: BucketAccessor["membersIterator"];
  on(kind: "enter", handler: BucketOnHandler<"enter">): DefinedBucket<Id>;
  on(
    kind: "enter",
    opts: EnterOptions,
    handler: BucketOnHandler<"enter">,
  ): DefinedBucket<Id>;
  on(kind: "leave", handler: BucketOnHandler<"leave">): DefinedBucket<Id>;
  on(
    kind: "leave",
    opts: LeaveOptions,
    handler: BucketOnHandler<"leave">,
  ): DefinedBucket<Id>;
  on(
    kind: "dwell",
    opts: DwellOptions,
    handler: BucketOnHandler<"dwell">,
  ): DefinedBucket<Id>;
}

export function defineBucket<const Id extends string>(options: {
  meta: BucketMetaInput<Id>;
}): DefinedBucket<Id> {
  // The ONLY transform defineBucket performs is resolving a builder-function
  // `criteria` to its `ConditionEval` (a one-shot, definition-time call). It does
  // NOT validate or build any task — `bucketMetaSchema.parse` still happens at
  // BucketRegistry.register, and the fast-expiry durableTask is synthesized later
  // by selectBucketTasks (Section 9.4). A declarative `criteria` passes straight
  // through unchanged, so existing buckets are unaffected.
  const { criteria, ...rest } = options.meta;
  const meta: BucketMeta = {
    ...rest,
    criteria:
      typeof criteria === "function" ? criteria(criteriaBuilder) : criteria,
  };

  // Pure string derivation — synchronous, no cross-module value binding (the
  // ESM-cycle resolution): entered/left are stable the instant defineBucket
  // returns, computed from meta.id, NOT bound to any other module's value.
  const entered = `bucket:entered:${meta.id}` as `bucket:entered:${Id}`;
  const left = `bucket:left:${meta.id}` as `bucket:left:${Id}`;
  const reactions: DefinedJourney[] = [];
  const accessor = createBucketAccessor(meta.id);

  const bucket: DefinedBucket<Id> = {
    meta,
    entered,
    left,
    reactions,
    count: accessor.count,
    has: accessor.has,
    members: accessor.members,
    membersIterator: accessor.membersIterator,
    on(kind: "enter" | "leave" | "dwell", a: unknown, b?: unknown) {
      const { opts, handler } = normalizeOnArgs(kind, a, b);
      reactions.push(
        buildBucketReaction({
          bucket: bucket as DefinedBucket,
          kind,
          opts,
          handler,
        }),
      );
      return bucket;
    },
  };
  return bucket;
}
