import { BucketRegistry } from "@hogsend/core/registry";
import type { DefinedJourney } from "../journeys/define-journey.js";
import { parseEnabledFilter } from "../journeys/registry.js";
import { bucketExpiryTask } from "../workflows/bucket-reconcile.js";
import type { DefinedBucket } from "./define-bucket.js";
import { setBucketRegistry } from "./registry-singleton.js";

/**
 * Build a {@link BucketRegistry} from an injected array of buckets, applying the
 * enabled filter, and install it as the process singleton (so the real-time
 * ingest path and the reconcile cron can resolve it). Returns the registry.
 *
 * `parseEnabledFilter` (journeys/registry.ts) is reused as-is — `ENABLED_BUCKETS`
 * honours the same `"*"`-or-csv contract as `ENABLED_JOURNEYS` (Section 9.3).
 * `BucketRegistry.register()` runs `bucketMetaSchema.parse()` internally, so no
 * separate validation step is needed here.
 */
export function buildBucketRegistry(
  buckets: DefinedBucket[],
  enabledFilter?: string,
): BucketRegistry {
  const registry = new BucketRegistry();
  const enabled = parseEnabledFilter(enabledFilter);

  for (const bucket of buckets) {
    if (enabled === "*" || enabled.has(bucket.meta.id)) {
      registry.register(bucket.meta);
    }
  }

  setBucketRegistry(registry);
  return registry;
}

/**
 * Select the Hatchet durable tasks for the enabled buckets. This is the SINGLE
 * place a bucket's per-user fast-expiry timer task is constructed (Section
 * 4.3/9.4) — task construction happens at worker build, AFTER the registry has
 * validated every meta, never at module-load.
 *
 * Only `meta.fastExpiry` buckets contribute a task; the engine-wide
 * `bucketReconcileTask` (registered separately in `baseWorkflows`) owns
 * time-based leaves regardless. The fast-expiry timer is a single shared
 * `durableTask` keyed on `bucket:arm-expiry` (per-bucket arming is by event
 * payload, not per-bucket task instances), so it is registered once if ANY
 * enabled bucket opts in.
 */
export function selectBucketTasks(
  buckets: DefinedBucket[],
  enabledFilter?: string,
): NonNullable<DefinedBucket["task"]>[] {
  const enabled = parseEnabledFilter(enabledFilter);
  const hasFastExpiry = buckets.some(
    (b) =>
      (enabled === "*" || enabled.has(b.meta.id)) && b.meta.fastExpiry === true,
  );
  if (!hasFastExpiry) return [];

  // The single shared `bucket:arm-expiry` durableTask, registered ONCE because
  // any enabled bucket opts in (per-bucket arming is by event payload). Cast to
  // the DefinedBucket task shape — both are `hatchet.durableTask` returns.
  return [bucketExpiryTask as NonNullable<DefinedBucket["task"]>];
}

/**
 * Select the Hatchet durable tasks for the reaction journeys generated by
 * `bucket.on()` across the ENABLED buckets (Section 9). Reactions are
 * bucket-owned, so they are gated by `ENABLED_BUCKETS` — NOT `ENABLED_JOURNEYS`
 * (their `bucket-<id>-on-<kind>` ids never appear in a consumer's
 * `ENABLED_JOURNEYS` csv, so folding them into the journeys[] array would drop
 * every reaction whenever ENABLED_JOURNEYS is a csv).
 *
 * Asserts no reaction-id collision (a build-time loud failure) before returning.
 */
export function selectBucketReactionTasks(
  buckets: DefinedBucket[],
  enabledFilter?: string,
  userJourneyIds?: Iterable<string>,
): NonNullable<DefinedBucket["task"]>[] {
  const enabled = parseEnabledFilter(enabledFilter);
  const enabledBuckets = buckets.filter(
    (b) => enabled === "*" || enabled.has(b.meta.id),
  );
  // Loud boot failure on a duplicate reaction id / user-journey collision
  // instead of a silent register-last-wins drop (Section 9). Pass the consumer
  // journey ids so a reaction id colliding with a hand-written journey throws.
  assertNoReactionIdCollisions(enabledBuckets, userJourneyIds);
  return enabledBuckets.flatMap((b) =>
    b.reactions.map((r) => r.task),
  ) as NonNullable<DefinedBucket["task"]>[];
}

/**
 * Collect the reaction `DefinedJourney`s across the ENABLED buckets (Section 9).
 * Bucket-gated by `ENABLED_BUCKETS` for the same reason as
 * {@link selectBucketReactionTasks}. The container registers their metas into the
 * journey registry directly (bypassing the ENABLED_JOURNEYS filter) so the admin
 * `feedsJourneys` and the dwell cron can resolve them.
 */
export function collectBucketReactionJourneys(
  buckets: DefinedBucket[],
  enabledFilter?: string,
): DefinedJourney[] {
  const enabled = parseEnabledFilter(enabledFilter);
  return buckets
    .filter((b) => enabled === "*" || enabled.has(b.meta.id))
    .flatMap((b) => b.reactions);
}

/**
 * Reaction tasks register on Hatchet under `journey-${meta.id}`. Two buckets
 * sharing an id, two reactions colliding on a generated id, or a user journey
 * named `bucket-<id>-on-<kind>` collide silently (register-last-wins) or throw on
 * boot. Throw a descriptive build-time error instead (Section 9).
 *
 * @param enabledBuckets the already-enabled buckets to scan.
 * @param userJourneyIds ids of the consumer's hand-written journeys (optional);
 *   a reaction id colliding with one of these throws.
 */
export function assertNoReactionIdCollisions(
  enabledBuckets: DefinedBucket[],
  userJourneyIds?: Iterable<string>,
): void {
  const seen = new Set<string>();
  const userIds = new Set(userJourneyIds ?? []);

  for (const bucket of enabledBuckets) {
    for (const reaction of bucket.reactions) {
      const id = reaction.meta.id;
      if (seen.has(id)) {
        throw new Error(
          `Bucket reaction id collision: "${id}" is generated by more than one reaction (check for duplicate bucket ids or two reactions of the same kind on bucket "${bucket.meta.id}").`,
        );
      }
      if (userIds.has(id)) {
        throw new Error(
          `Bucket reaction id collision: generated reaction "${id}" (bucket "${bucket.meta.id}") collides with a user journey of the same id.`,
        );
      }
      seen.add(id);
    }
  }
}
