/**
 * Compile-time proof that `flags.d.ts` (generated by `hogsend flags generate`)
 * augments `FlagRegistryMap` for THIS app. This file is type-only — it renders
 * nothing and is never imported at runtime; it exists so `pnpm check-types`
 * fails loudly if the codegen regresses.
 */

import type { FlagKey, FlagRegistryMap } from "@hogsend/core";

// The generated flag key is a KNOWN `FlagKey`. If the augmentation regressed to
// an empty registry, `FlagKey` would be `never` and this line would error.
const _known: FlagKey = "docs-preview-banner";

// A bogus key is NOT assignable — the `@ts-expect-error` MUST fire. (If the
// registry regressed to empty, `FlagKey` = `never`, the assignment still errors,
// and the directive is still satisfied — so this stays green only when the
// augmentation is present AND rejects typos.)
// @ts-expect-error "nope" is not a declared flag key
const _bad: FlagKey = "nope";

// The boolean flag's served VALUE TYPE is `boolean` (not `unknown`).
type _AssertBoolean = FlagRegistryMap["docs-preview-banner"] extends boolean
  ? true
  : never;
const _valueIsBoolean: _AssertBoolean = true;

void _known;
void _bad;
void _valueIsBoolean;
