// Generated by `hogsend flags generate` — DO NOT EDIT BY HAND.
// Regenerate whenever src/flags/index.ts changes. Augments FlagRegistryMap in
// @hogsend/core so useFlag()/useFlags() (@hogsend/react), hogsend.getFlag()
// (@hogsend/js), and client.flags.evaluate() (@hogsend/client) type-check this
// app's flag keys and narrow their served values.

import "@hogsend/core";

declare module "@hogsend/core" {
  interface FlagRegistryMap {
    "docs-preview-banner": boolean;
  }
}
