import { OpenAPIHono } from "@hono/zod-openapi";
import type { AppEnv } from "../../app.js";
import { requireApiKey } from "../../middleware/api-key.js";
import { contactsRouter } from "./contacts.js";
import { emailsRouter } from "./emails.js";
import { eventsRouter } from "./events.js";
import { journeyLogsRouter } from "./journey-logs.js";
import { journeysRouter } from "./journeys.js";
import { preferencesRouter } from "./preferences.js";
import { timelineRouter } from "./timeline.js";

export const adminRouter = new OpenAPIHono<AppEnv>();
adminRouter.use("*", requireApiKey);
adminRouter.route("/contacts", contactsRouter);
adminRouter.route("/contacts", preferencesRouter);
adminRouter.route("/contacts", timelineRouter);
adminRouter.route("/journeys", journeysRouter);
adminRouter.route("/events", eventsRouter);
adminRouter.route("/emails", emailsRouter);
adminRouter.route("/journey-logs", journeyLogsRouter);
