import type { DefinedBucket } from "./buckets/define-bucket.js";
import {
  collectBucketReactionJourneys,
  selectBucketReactionTasks,
  selectBucketTasks,
} from "./buckets/registry.js";
import type { DefinedCampaign } from "./campaigns/define-campaign.js";
import { reconcileDefinedCampaigns } from "./campaigns/reconcile.js";
import {
  type ConnectorRuntimeFactory,
  startConnectorRuntimes,
} from "./connectors/runtime.js";
import type { HogsendClient } from "./container.js";
import type { DefinedJourney } from "./journeys/define-journey.js";
import { parseEnabledFilter, selectJourneyTasks } from "./journeys/registry.js";
import { reportWorkerReady } from "./lib/boot.js";
import { hatchet } from "./lib/hatchet.js";
import { getRedisIfConnected } from "./lib/redis.js";
import { startWorkerHeartbeat } from "./lib/worker-heartbeat.js";
import {
  bucketBackfillTask,
  enqueueBucketBackfills,
} from "./workflows/bucket-backfill.js";
import { bucketReconcileTask } from "./workflows/bucket-reconcile.js";
import { checkAlertsTask } from "./workflows/check-alerts.js";
import { confirmSemanticClickTask } from "./workflows/confirm-semantic-click.js";
import { crmReconcileTask } from "./workflows/crm-reconcile.js";
import {
  deliverWebhookTask,
  reapDueWebhookDeliveriesTask,
} from "./workflows/deliver-webhook.js";
import { importContactsTask } from "./workflows/import-contacts.js";
import { importSuppressionsTask } from "./workflows/import-suppressions.js";
import { journeyBlueprintInterpreter } from "./workflows/journey-blueprint-interpreter.js";
import {
  reapStuckCampaignsTask,
  sendCampaignTask,
} from "./workflows/send-campaign.js";
import { sendEmailTask } from "./workflows/send-email.js";
import { sendFeedTask } from "./workflows/send-feed.js";

export interface CreateWorkerOptions {
  container: HogsendClient;
  journeys: DefinedJourney[];
  /** Buckets whose fast-expiry timer tasks are registered. Defaults to none. */
  buckets?: DefinedBucket[];
  /**
   * Code-defined one-shot campaigns (broadcasts) reconciled at boot into
   * scheduled `campaigns` rows. Defaults to `container.campaigns`.
   */
  campaigns?: DefinedCampaign[];
  /** Defaults to `container.env.ENABLED_JOURNEYS`. */
  enabledJourneys?: string;
  /** Defaults to `container.env.ENABLED_BUCKETS`. */
  enabledBuckets?: string;
  /** Extra client tasks registered alongside the built-in workflows. */
  extraWorkflows?: unknown[];
  /**
   * Inbound connector-runtime factories keyed by connector id (e.g.
   * `{ discord: createDiscordRuntime }`). When `CONNECTOR_RUNTIME_HOST=worker`
   * (default) and `ENABLE_CONNECTOR_RUNTIMES` is on, the worker elects a single
   * leader replica per gateway connector and holds its socket inline — no
   * separate service, no ingress secret.
   */
  connectorRuntimes?: Record<string, ConnectorRuntimeFactory>;
}

export interface Worker {
  start(): Promise<void>;
  stop(): Promise<void>;
}

export function createWorker(opts: CreateWorkerOptions): Worker {
  const { container, journeys } = opts;
  const enabled = opts.enabledJourneys ?? container.env.ENABLED_JOURNEYS;
  const enabledBuckets = opts.enabledBuckets ?? container.env.ENABLED_BUCKETS;
  // Bucket-reaction journey ids (`bucket-<id>-on-<kind>`) are registered
  // separately (via selectBucketReactionTasks) bypassing ENABLED_JOURNEYS, but
  // they ARE registered journeys — include them in the known set so listing a
  // real reaction id in ENABLED_JOURNEYS is not rejected as an unknown-id typo.
  const reactionJourneyIds = collectBucketReactionJourneys(
    opts.buckets ?? [],
    enabledBuckets,
  ).map((r) => r.meta.id);
  const journeyTasks = selectJourneyTasks(
    journeys,
    enabled,
    reactionJourneyIds,
  );
  // The enabled journey IDs, logged at startup so a stale worker (one missing a
  // newly added journey because the dev watcher never restarted it) is visible
  // at a glance — counts alone can't show WHICH journeys are registered.
  const journeyFilter = parseEnabledFilter(enabled);
  const journeyIds = journeys
    .filter((j) => journeyFilter === "*" || journeyFilter.has(j.meta.id))
    .map((j) => j.meta.id);

  // The single place a bucket's per-user fast-expiry timer task is constructed
  // (Section 9.4): the shared `bucket:arm-expiry` durableTask, registered once iff
  // any enabled bucket opts into fastExpiry. The engine-wide time-based-leave
  // reconcile cron (bucketReconcileTask) is ALWAYS registered in baseWorkflows
  // below (Section 10), regardless of fastExpiry.
  const bucketTasks = selectBucketTasks(opts.buckets ?? [], enabledBuckets);
  // Reaction journeys generated by `bucket.on()` desugar to real durable tasks.
  // They are bucket-owned, so they are gated by ENABLED_BUCKETS (NOT
  // ENABLED_JOURNEYS) and wired directly here rather than via the journeys[]
  // array (Section 9). Throws loudly on a reaction-id collision.
  const bucketReactionTasks = selectBucketReactionTasks(
    opts.buckets ?? [],
    enabledBuckets,
    journeys.map((j) => j.meta.id),
  );

  const baseWorkflows = [
    sendEmailTask,
    sendFeedTask,
    importContactsTask,
    importSuppressionsTask,
    // The generic blueprint interpreter — registered ONCE, always, like every
    // other built-in. Blueprint content never changes worker registration:
    // dispatch is a DB lookup at ingest (checkBlueprintTriggers, spec §5).
    journeyBlueprintInterpreter,
    sendCampaignTask,
    reapStuckCampaignsTask,
    deliverWebhookTask,
    reapDueWebhookDeliveriesTask,
    confirmSemanticClickTask,
    checkAlertsTask,
    bucketReconcileTask,
    bucketBackfillTask,
    crmReconcileTask,
    ...journeyTasks,
    ...bucketTasks,
    ...bucketReactionTasks,
  ];
  const workflows = [
    ...baseWorkflows,
    ...((opts.extraWorkflows ?? []) as typeof baseWorkflows),
  ];

  // Hatchet's worker is created lazily on start so signal wiring can own its
  // lifecycle. `_worker` is captured for stop().
  let _worker: Awaited<ReturnType<typeof hatchet.worker>> | undefined;
  let _stopHeartbeat: (() => Promise<void>) | undefined;
  let _stopRuntimes: (() => Promise<void>) | undefined;

  async function stop(): Promise<void> {
    // Delete the worker heartbeat first (an immediate "worker down" signal) and
    // release any connector-runtime leases + their heartbeats BEFORE the Redis
    // connection is torn down below.
    await _stopHeartbeat?.();
    await _stopRuntimes?.();
    await Promise.allSettled([
      _worker?.stop(),
      // Shut down the injected analytics instance (same object the worker's
      // tasks use), not the module singleton. Undefined when no analytics is
      // configured, and `shutdown` is optional on the provider contract —
      // both optional chains make that a no-op.
      container.analytics?.shutdown?.(),
      getRedisIfConnected()?.quit(),
    ]);
  }

  async function start(): Promise<void> {
    // Emit BEFORE the Hatchet handshake: proves the process booted past init
    // even while the connection is still establishing (the worker banner /
    // "ready" line only fires once `hatchet.worker()` resolves).
    container.logger.info("Hogsend worker starting", {
      hatchet: container.env.HATCHET_CLIENT_HOST_PORT,
      journeys: journeyIds,
    });

    _worker = await hatchet.worker("hogsend-worker", { workflows });

    reportWorkerReady({
      client: container,
      journeyTasks: journeyTasks.length,
      bucketTasks: bucketTasks.length,
      bucketReactionTasks: bucketReactionTasks.length,
      builtinTasks:
        baseWorkflows.length -
        journeyTasks.length -
        bucketTasks.length -
        bucketReactionTasks.length,
    });

    // Publish liveness so the API + Studio can show "worker connected"
    // (read via GET /v1/health). Best-effort; never blocks the listener.
    _stopHeartbeat = startWorkerHeartbeat(container.logger);

    // Inline connector runtimes (gateway sockets) — the worker is the default
    // host. Each gateway connector with a supplied factory races a Redis leader
    // lease so exactly one replica holds its socket; the in-process sink feeds
    // transform→ingest with no HTTP hop. Auto-on; a factory that declines (e.g.
    // no bot token) simply no-ops. Started AFTER the heartbeat and BEFORE the
    // blocking `_worker.start()` below (anything after it is dead code at
    // runtime until shutdown).
    if (
      container.env.ENABLE_CONNECTOR_RUNTIMES === "true" &&
      container.env.CONNECTOR_RUNTIME_HOST === "worker" &&
      opts.connectorRuntimes &&
      Object.keys(opts.connectorRuntimes).length > 0
    ) {
      const runtimes = startConnectorRuntimes({
        client: container,
        factories: opts.connectorRuntimes,
      });
      _stopRuntimes = () => runtimes.stop();
    }

    // Boot-time backfill / criteria-change re-eval (Section 6.6 B): diff each
    // enabled bucket's criteriaHash against bucket_configs and trigger a
    // backfill/re-eval run where it differs. Kicked off BEFORE the listener
    // because `_worker.start()` below does NOT return until the worker stops —
    // anything after it is dead code at runtime. The triggers are fire-and-forget
    // (runNoWait) and execute once the listener is up; best-effort, never blocks.
    enqueueBucketBackfills({
      db: container.db,
      logger: container.logger,
    }).catch((err) => {
      container.logger.warn("Bucket backfill enqueue (boot) failed", {
        error: err instanceof Error ? err.message : String(err),
      });
    });

    // Reconcile code-defined campaigns into scheduled rows (create / sync /
    // expire — see `reconcileDefinedCampaigns`). Same fire-and-forget stance
    // as the bucket backfills above: best-effort, never blocks the listener.
    const definedCampaigns = opts.campaigns ?? container.campaigns;
    if (definedCampaigns.length > 0) {
      reconcileDefinedCampaigns({
        client: container,
        campaigns: definedCampaigns,
      }).catch((err) => {
        container.logger.warn("Campaign reconcile (boot) failed", {
          error: err instanceof Error ? err.message : String(err),
        });
      });
    }

    await _worker.start();
  }

  return { start, stop };
}
