import { OpenAPIHono } from "@hono/zod-openapi";
import type { AppEnv } from "../../app.js";
import { auditMiddleware } from "../../middleware/audit.js";
import { rateLimit } from "../../middleware/rate-limit.js";
import { requireAdmin } from "../../middleware/require-admin.js";
import { agentRouter } from "./agent.js";
import { alertsRouter } from "./alerts.js";
import { analyticsAdminRouter } from "./analytics.js";
import { apiKeysRouter } from "./api-keys.js";
import { adminAttributionRouter } from "./attribution.js";
import { auditLogsRouter } from "./audit-logs.js";
import { blueprintsRouter } from "./blueprints.js";
import { bucketsRouter } from "./buckets.js";
import { bulkRouter } from "./bulk.js";
import { adminCampaignsRouter } from "./campaigns.js";
import { adminConnectorsRouter } from "./connectors.js";
import { contactsRouter } from "./contacts.js";
import { adminConversionsRouter } from "./conversions.js";
import { adminDealsRouter } from "./deals.js";
import { dlqRouter } from "./dlq.js";
import { domainRouter } from "./domain.js";
import { emailsRouter } from "./emails.js";
import { eventsRouter } from "./events.js";
import { adminFunnelsRouter } from "./funnels.js";
import { groupsRouter } from "./groups.js";
import { journeyLogsRouter } from "./journey-logs.js";
import { journeysRouter } from "./journeys.js";
import { linksRouter } from "./links.js";
import { adminListsRouter } from "./lists.js";
import { metricsRouter } from "./metrics.js";
import { openEditorRouter } from "./open-editor.js";
import { preferencesRouter } from "./preferences.js";
import { providerCredentialsRouter } from "./provider-credentials.js";
import { readinessRouter } from "./readiness.js";
import { reportingRouter } from "./reporting.js";
import { settingsRouter } from "./settings.js";
import { suppressionsRouter } from "./suppressions.js";
import { templatesRouter } from "./templates.js";
import { timelineRouter } from "./timeline.js";
import { webhooksRouter } from "./webhooks.js";

export const adminRouter = new OpenAPIHono<AppEnv>();
adminRouter.use("*", requireAdmin);
adminRouter.use("*", rateLimit);
adminRouter.use("*", auditMiddleware);
adminRouter.route("/", bulkRouter);
adminRouter.route("/contacts", contactsRouter);
adminRouter.route("/contacts", preferencesRouter);
adminRouter.route("/contacts", timelineRouter);
adminRouter.route("/journeys", journeysRouter);
adminRouter.route("/blueprints", blueprintsRouter);
adminRouter.route("/open-in-editor", openEditorRouter);
adminRouter.route("/buckets", bucketsRouter);
adminRouter.route("/lists", adminListsRouter);
adminRouter.route("/campaigns", adminCampaignsRouter);
adminRouter.route("/deals", adminDealsRouter);
adminRouter.route("/conversions", adminConversionsRouter);
adminRouter.route("/attribution", adminAttributionRouter);
adminRouter.route("/funnels", adminFunnelsRouter);
adminRouter.route("/groups", groupsRouter);
adminRouter.route("/events", eventsRouter);
adminRouter.route("/emails", emailsRouter);
adminRouter.route("/links", linksRouter);
adminRouter.route("/journey-logs", journeyLogsRouter);
adminRouter.route("/metrics", metricsRouter);
adminRouter.route("/reporting", reportingRouter);
adminRouter.route("/templates", templatesRouter);
adminRouter.route("/settings", settingsRouter);
adminRouter.route("/suppressions", suppressionsRouter);
adminRouter.route("/api-keys", apiKeysRouter);
adminRouter.route("/webhooks", webhooksRouter);
adminRouter.route("/provider-credentials", providerCredentialsRouter);
adminRouter.route("/connectors", adminConnectorsRouter);
adminRouter.route("/analytics", analyticsAdminRouter);
adminRouter.route("/audit-logs", auditLogsRouter);
adminRouter.route("/alerts", alertsRouter);
adminRouter.route("/dlq", dlqRouter);
adminRouter.route("/domain", domainRouter);
adminRouter.route("/readiness", readinessRouter);
adminRouter.route("/agent", agentRouter);
