import { OpenAPIHono } from "@hono/zod-openapi";
import type { AppEnv } from "../../app.js";
import { auditMiddleware } from "../../middleware/audit.js";
import { rateLimit } from "../../middleware/rate-limit.js";
import { requireAdmin } from "../../middleware/require-admin.js";
import { alertsRouter } from "./alerts.js";
import { apiKeysRouter } from "./api-keys.js";
import { auditLogsRouter } from "./audit-logs.js";
import { bucketsRouter } from "./buckets.js";
import { bulkRouter } from "./bulk.js";
import { contactsRouter } from "./contacts.js";
import { dlqRouter } from "./dlq.js";
import { domainRouter } from "./domain.js";
import { emailsRouter } from "./emails.js";
import { eventsRouter } from "./events.js";
import { journeyLogsRouter } from "./journey-logs.js";
import { journeysRouter } from "./journeys.js";
import { metricsRouter } from "./metrics.js";
import { preferencesRouter } from "./preferences.js";
import { reportingRouter } from "./reporting.js";
import { suppressionsRouter } from "./suppressions.js";
import { templatesRouter } from "./templates.js";
import { timelineRouter } from "./timeline.js";
import { webhooksRouter } from "./webhooks.js";

export const adminRouter = new OpenAPIHono<AppEnv>();
adminRouter.use("*", requireAdmin);
adminRouter.use("*", rateLimit);
adminRouter.use("*", auditMiddleware);
adminRouter.route("/", bulkRouter);
adminRouter.route("/contacts", contactsRouter);
adminRouter.route("/contacts", preferencesRouter);
adminRouter.route("/contacts", timelineRouter);
adminRouter.route("/journeys", journeysRouter);
adminRouter.route("/buckets", bucketsRouter);
adminRouter.route("/events", eventsRouter);
adminRouter.route("/emails", emailsRouter);
adminRouter.route("/journey-logs", journeyLogsRouter);
adminRouter.route("/metrics", metricsRouter);
adminRouter.route("/reporting", reportingRouter);
adminRouter.route("/templates", templatesRouter);
adminRouter.route("/suppressions", suppressionsRouter);
adminRouter.route("/api-keys", apiKeysRouter);
adminRouter.route("/webhooks", webhooksRouter);
adminRouter.route("/audit-logs", auditLogsRouter);
adminRouter.route("/alerts", alertsRouter);
adminRouter.route("/dlq", dlqRouter);
adminRouter.route("/domain", domainRouter);
