import {
  existsSync,
  mkdirSync,
  readdirSync,
  rmSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { basename, extname, join, relative, resolve } from "node:path";
import type { JourneyGraph } from "@hogsend/core";
import { renderMermaid } from "@hogsend/core";
import { extractJourneyGraph, extractJourneyId } from "./journey-graph.js";

/**
 * Docs/manifest generator for `hogsend journeys graph --all`.
 *
 * Three artifacts, all derived from the same source walk:
 *   1. A GitHub-native Markdown file (one section per journey, fenced mermaid).
 *   2. (optional) A Fumadocs mirror under the docs content dir + sidebar entry.
 *   3. A structured manifest (`.hogsend/journeys.graph.json`) the admin route
 *      reads at boot so Studio can render the rich graph with live counts.
 */

export interface GenerateOptions {
  /** Directory holding journey `.ts` files. */
  source: string;
  /** Where to write the standalone Markdown file. */
  out?: string;
  /** Fumadocs content dir to mirror into (enables the docs-site page). */
  fumadocs?: string;
  /** Where to write the structured manifest. */
  manifest?: string;
  /**
   * Write the standalone Markdown file (default true). Set false for a
   * manifest-only run — e.g. the build/pre-deploy step that only needs the
   * admin route's manifest and should not drop a stray `docs/journeys.md`.
   */
  markdown?: boolean;
  /** Current working directory, for resolving relative paths in messages. */
  cwd?: string;
}

export interface GenerateResult {
  journeys: number;
  markdownPath?: string;
  fumadocsPath?: string;
  manifestPath?: string;
}

/** Default output locations relative to the project root. */
const DEFAULT_OUT = "docs/journeys.md";
const DEFAULT_MANIFEST = ".hogsend/journeys.graph.json";

/**
 * Scan a directory for journey `.ts` files. Returns absolute paths. Only
 * `.ts` files are considered; `index.ts` barrels and `constants/` dirs are
 * skipped because they don't define a journey directly (constants files would
 * otherwise fail id-extraction and pollute the skipped report).
 */
export function discoverJourneyFiles(sourceDir: string): string[] {
  const out: string[] = [];
  if (!existsSync(sourceDir)) return out;
  const walk = (dir: string) => {
    for (const entry of readdirSync(dir)) {
      const full = join(dir, entry);
      const st = statSync(full);
      if (st.isDirectory()) {
        if (entry === "constants") continue;
        walk(full);
      } else if (st.isFile() && extname(full) === ".ts") {
        const base = basename(full);
        if (base === "index.ts") continue;
        out.push(full);
      }
    }
  };
  walk(sourceDir);
  return out.sort();
}

/**
 * Extract graphs for every journey found under `sourceDir`. Files without a
 * recognizable `defineJourney({ run })` are skipped (reported in `skipped`).
 * `relativeTo` (usually the project root) relativizes each graph's
 * `sourceFile` so the manifest carries portable code pointers.
 */
export function extractAll(
  sourceDir: string,
  relativeTo?: string,
): {
  graphs: JourneyGraph[];
  skipped: string[];
} {
  const files = discoverJourneyFiles(sourceDir);
  const graphs: JourneyGraph[] = [];
  const skipped: string[] = [];
  for (const file of files) {
    const id = extractJourneyId(file);
    if (!id) {
      skipped.push(file);
      continue;
    }
    try {
      const graph = extractJourneyGraph(file);
      graph.sourceFile = relativeTo ? relative(relativeTo, file) : file;
      graphs.push(graph);
    } catch (err) {
      skipped.push(`${file} (${(err as Error).message})`);
    }
  }
  // Stable order by journey id.
  graphs.sort((a, b) => a.journeyId.localeCompare(b.journeyId));
  return { graphs, skipped };
}

/** A short, human description of a node kind, for the legend table. */
function kindLabel(kind: JourneyGraph["nodes"][number]["kind"]): string {
  const map: Record<string, string> = {
    trigger: "Trigger (entry event)",
    email: "Email send",
    inapp: "In-app message",
    connector: "Connector action",
    sleep: "Sleep (durable delay)",
    schedule: "Scheduled wait",
    wait: "Wait for event",
    branch: "Branch (condition)",
    "trigger-event": "Emitted trigger",
    checkpoint: "Checkpoint",
    exit: "Exit event",
    end: "End",
  };
  return map[kind] ?? kind;
}

/**
 * Build the GitHub-native Markdown body: one section per journey with a meta
 * summary table and a fenced mermaid block, plus a shared legend.
 */
export function renderJourneysMarkdown(graphs: JourneyGraph[]): string {
  const lines: string[] = [];
  lines.push("# Journeys");
  lines.push("");
  lines.push(
    "Auto-generated by `hogsend journeys graph --all`. Each diagram is the authored control flow inside the journey's `run()`, extracted from source.",
  );
  lines.push("");

  // Legend
  lines.push("## Legend");
  lines.push("");
  lines.push("| Node | Meaning |");
  lines.push("| --- | --- |");
  const legendKinds: JourneyGraph["nodes"][number]["kind"][] = [
    "trigger",
    "email",
    "inapp",
    "connector",
    "sleep",
    "wait",
    "branch",
    "trigger-event",
    "checkpoint",
    "exit",
    "end",
  ];
  for (const k of legendKinds) {
    lines.push(`| \`${k}\` | ${kindLabel(k)} |`);
  }
  lines.push("");

  // Table of contents
  if (graphs.length > 0) {
    lines.push("## Journeys");
    lines.push("");
    for (const g of graphs) {
      const anchor = g.journeyId.toLowerCase().replace(/[^a-z0-9]+/g, "-");
      lines.push(`- [${g.journeyId}](#${anchor})`);
    }
    lines.push("");
  }

  // One section per journey
  for (const g of graphs) {
    lines.push(`## ${g.journeyId}`);
    lines.push("");
    const trigger = g.nodes.find((n) => n.kind === "trigger");
    const exits = g.nodes.filter((n) => n.kind === "exit");
    lines.push("| | |");
    lines.push("| --- | --- |");
    lines.push(`| Trigger | \`${trigger?.label ?? "?"}\` |`);
    if (exits.length > 0) {
      lines.push(
        `| Exit on | ${exits.map((e) => `\`${e.label}\``).join(", ")} |`,
      );
    }
    lines.push(`| Nodes | ${g.nodes.length} |`);
    lines.push(`| Fidelity | ${g.sourceLevel} |`);
    lines.push("");
    lines.push("```mermaid");
    lines.push(renderMermaid(g));
    lines.push("```");
    lines.push("");
    if (g.disclaimer) {
      lines.push(`> ${g.disclaimer}`);
      lines.push("");
    }
  }

  if (graphs.length === 0) {
    lines.push("_No journeys found._");
    lines.push("");
  }

  return lines.join("\n");
}

/** Build the structured manifest payload. */
export function renderManifest(graphs: JourneyGraph[]): string {
  const payload = {
    version: 1,
    generatedAt: new Date().toISOString(),
    journeys: graphs,
  };
  return `${JSON.stringify(payload, null, 2)}\n`;
}

/**
 * Build the Fumadocs mirror: an `index.mdx` page + a `meta.json` sidebar entry,
 * written under `<fumadocs>/journeys/`.
 */
function writeFumadocs(fumadocsDir: string, graphs: JourneyGraph[]): string {
  const dir = join(fumadocsDir, "journeys");
  rmSync(dir, { recursive: true, force: true });
  mkdirSync(dir, { recursive: true });

  const mdx: string[] = [];
  mdx.push("---");
  mdx.push('title: "Journeys"');
  mdx.push(
    'description: "Every journey\'s authored control flow, auto-generated."',
  );
  mdx.push("---");
  mdx.push("");
  mdx.push(
    "Auto-generated by `hogsend journeys graph --all`. Each diagram is the control flow inside a journey's `run()`, extracted from source.",
  );
  mdx.push("");
  for (const g of graphs) {
    mdx.push(`## ${g.journeyId}`);
    mdx.push("");
    mdx.push("```mermaid");
    mdx.push(renderMermaid(g));
    mdx.push("```");
    mdx.push("");
    if (g.disclaimer) {
      mdx.push(`> ${g.disclaimer}`);
      mdx.push("");
    }
  }
  writeFileSync(join(dir, "index.mdx"), mdx.join("\n"), "utf8");

  const meta = { title: "Journeys", pages: ["index"] };
  writeFileSync(
    join(dir, "meta.json"),
    `${JSON.stringify(meta, null, 2)}\n`,
    "utf8",
  );

  return dir;
}

/** Ensure the parent directory of a file path exists. */
function ensureDirFor(filePath: string): void {
  mkdirSync(resolve(filePath, ".."), { recursive: true });
}

/**
 * Run the full generation: discover journeys, extract graphs, write the
 * Markdown file, optional Fumadocs mirror, and manifest. Returns a summary.
 */
export function generateAll(opts: GenerateOptions): GenerateResult & {
  skipped: string[];
  warnings: string[];
} {
  const cwd = opts.cwd ?? process.cwd();
  const source = resolve(cwd, opts.source);
  const { graphs, skipped } = extractAll(source, cwd);
  const warnings: string[] = [];

  const result: GenerateResult & { skipped: string[]; warnings: string[] } = {
    journeys: graphs.length,
    skipped,
    warnings,
  };

  // 1. Standalone Markdown (skippable for manifest-only runs).
  if (opts.markdown !== false) {
    const outPath = resolve(cwd, opts.out ?? DEFAULT_OUT);
    ensureDirFor(outPath);
    writeFileSync(outPath, renderJourneysMarkdown(graphs), "utf8");
    result.markdownPath = relative(cwd, outPath);
  }

  // 2. Fumadocs mirror.
  if (opts.fumadocs) {
    const fumadocsDir = resolve(cwd, opts.fumadocs);
    if (existsSync(fumadocsDir)) {
      const written = writeFumadocs(fumadocsDir, graphs);
      result.fumadocsPath = relative(cwd, written);
    } else {
      warnings.push(
        `--fumadocs dir not found, mirror skipped: ${relative(cwd, fumadocsDir)}`,
      );
    }
  }

  // 3. Manifest.
  const manifestPath = resolve(cwd, opts.manifest ?? DEFAULT_MANIFEST);
  ensureDirFor(manifestPath);
  writeFileSync(manifestPath, renderManifest(graphs), "utf8");
  result.manifestPath = relative(cwd, manifestPath);

  return result;
}
