export { HogsendAPIError, RateLimitError } from "./errors.js";
export { Hogsend } from "./hogsend.js";
export type {
  Campaign,
  CampaignAudienceKind,
  CampaignStatus,
  Contact,
  DeleteContactInput,
  DeleteContactResult,
  ExitResult,
  FindContactsInput,
  HogsendOptions,
  Identity,
  IngestResult,
  ListSummary,
  SendCampaignInput,
  SendCampaignResult,
  SendEmailInput,
  SendEmailResult,
  SendEventInput,
  SubscribeInput,
  SubscribeResult,
  UnsubscribeResult,
  UpsertContactInput,
  UpsertContactResult,
} from "./types.js";
